/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Projects {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface WorkspaceMembers {
  created_at: Generated<Timestamp>;
  role: string;
  user_id: string;
  workspace_id: string;
}

export interface Workspaces {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface DB {
  projects: Projects;
  workspace_members: WorkspaceMembers;
  workspaces: Workspaces;
}
