/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AgentExecutions {
  agent: string;
  agent_version: string;
  attempt: number;
  cost_usd_micros: Generated<Int8>;
  ended_at: Timestamp | null;
  failure: Json | null;
  id: Generated<string>;
  input: Json;
  input_tokens: Generated<Int8>;
  lease_token: string;
  limits: Json;
  llm_calls: Generated<number>;
  output: Json | null;
  output_tokens: Generated<Int8>;
  prompt_hash: string;
  run_id: string;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
  task_id: string;
  tool_calls: Generated<number>;
  turns: Generated<number>;
  workspace_id: string;
}

export interface AgentMessages {
  content: Json;
  created_at: Generated<Timestamp>;
  execution_id: string;
  role: string;
  seq: number;
  workspace_id: string;
}

export interface Approvals {
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision: string | null;
  decision_reason: string | null;
  id: Generated<string>;
  invalidated_at: Timestamp | null;
  invalidation_detail: string | null;
  invalidation_reason: string | null;
  replaced_by: string | null;
  requested_at: Generated<Timestamp>;
  run_id: string;
  snapshot: Json;
  snapshot_hash: string;
  snapshot_hash_seen: string | null;
  snapshot_schema_version: number;
  status: Generated<string>;
  target: Json;
  target_key: string;
  task_id: string | null;
  type: string;
  workspace_id: string;
}

export interface AuditLogs {
  action: string;
  actor: Json;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  metadata: Generated<Json>;
  target_id: string | null;
  target_type: string | null;
  workspace_id: string;
}

export interface DiscoveredUrls {
  discovered_at: Generated<Timestamp>;
  id: Generated<string>;
  normalized_url: string;
  normalized_url_hash: string;
  origin: Json;
  origin_kind: string;
  run_id: string;
  url: string;
  workspace_id: string;
}

export interface LlmCalls {
  cache_read_tokens: Int8 | null;
  cache_status: string;
  cache_write_tokens: Int8 | null;
  cost_usd_micros: Int8;
  execution_id: string;
  failure: Json | null;
  id: string;
  input_tokens: Int8;
  latency_ms: number;
  model: string;
  output_tokens: Int8;
  prompt_version: string;
  provider: string;
  provider_account: string;
  reasoning_tokens: Int8 | null;
  request_hash: string;
  retry_count: number;
  route: string;
  routing_config_version: string;
  run_id: string;
  seq: number;
  started_at: Timestamp;
  stop_reason: string;
  task_id: string;
  workspace_id: string;
}

export interface Projects {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface RunEvents {
  actor: Json;
  data: Generated<Json>;
  occurred_at: Generated<Timestamp>;
  refs: Generated<Json>;
  run_id: string;
  seq: Int8;
  type: string;
  workspace_id: string;
}

export interface Runs {
  brief: Json | null;
  budget: Json;
  budget_blocked: Generated<boolean>;
  cancel_requested: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string;
  failure: Json | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  last_event_seq: Generated<Int8>;
  objective: string;
  pause_reason: string | null;
  pause_requested: Generated<boolean>;
  project_id: string;
  spend_cost_usd_micros: Generated<Int8>;
  spend_llm_input_tokens: Generated<Int8>;
  spend_llm_output_tokens: Generated<Int8>;
  spend_tool_calls: Generated<number>;
  started_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  workflow: string;
  workflow_version: number;
  workspace_id: string;
}

export interface Sources {
  canonical_url: string | null;
  content_sha256: string;
  created_at: Generated<Timestamp>;
  discovered_url_id: string | null;
  extraction_method: string;
  extractor_version: string;
  fetched_by_tool_call_id: string;
  final_url: string;
  final_url_hash: string;
  flags: Generated<string[]>;
  host: string;
  http: Json | null;
  id: Generated<string>;
  language: string | null;
  origin: Json;
  published_at: Timestamp | null;
  published_at_method: string;
  publisher: string | null;
  raw_sha256: string;
  registrable_domain: string;
  requested_url: string;
  retrieved_at: Timestamp;
  source_type: string;
  text: string;
  text_length: number;
  tier: string;
  title: string | null;
  truncated: boolean;
  workspace_id: string;
}

export interface TaskDependencies {
  created_at: Generated<Timestamp>;
  depends_on_task_id: string;
  mode: string;
  run_id: string;
  task_id: string;
  workspace_id: string;
}

export interface Tasks {
  attempt: Generated<number>;
  created_at: Generated<Timestamp>;
  finished_at: Timestamp | null;
  heartbeat_at: Timestamp | null;
  id: Generated<string>;
  idempotency_key: string;
  input: Json;
  kind: string;
  last_failure: Json | null;
  lease_expires_at: Timestamp | null;
  lease_owner: string | null;
  lease_token: string | null;
  max_attempts: number;
  output: Json | null;
  parent_task_id: string | null;
  priority: Generated<number>;
  run_after: Generated<Timestamp>;
  run_id: string;
  started_at: Timestamp | null;
  status: Generated<string>;
  subject_company_id: string | null;
  type: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface ToolCalls {
  arguments: Json;
  arguments_hash: string;
  cache_hit: Generated<boolean>;
  cost_usd_micros: Generated<Int8>;
  created_source_ids: Generated<string[]>;
  error_code: string | null;
  execution_id: string;
  id: string;
  latency_ms: number;
  model_tool_call_id: string | null;
  provider: string | null;
  run_id: string;
  started_at: Timestamp;
  status: string;
  task_id: string;
  tool: string;
  upstream_latency_ms: number | null;
  workspace_id: string;
}

export interface WorkspaceMembers {
  created_at: Generated<Timestamp>;
  role: string;
  user_id: string;
  workspace_id: string;
}

export interface Workspaces {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface DB {
  agent_executions: AgentExecutions;
  agent_messages: AgentMessages;
  approvals: Approvals;
  audit_logs: AuditLogs;
  discovered_urls: DiscoveredUrls;
  llm_calls: LlmCalls;
  projects: Projects;
  run_events: RunEvents;
  runs: Runs;
  sources: Sources;
  task_dependencies: TaskDependencies;
  tasks: Tasks;
  tool_calls: ToolCalls;
  workspace_members: WorkspaceMembers;
  workspaces: Workspaces;
}
